name: Desplegar React vite en github pages

on:
  push:
    tags:
      - "dev-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: seleccionar al version de nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Establecer variable GITHUB_ACTIONS
        run: echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV

      - name: Instalar dependencias y construir el dist
        working-directory: ./src
        run: |
          pnpm install
          pnpm run build

      - name: Desplegar el dist en GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npx gh-pages -d dist -t $GITHUB_TOKEN
